version: "3.8"


services: 
    drone-ui:
        container_name: drone
        image: drone/drone:1
        env_file: .env
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - drone-data:/data

    drone-runner:
        container_name: dronerunner1
        restart: unless-stopped
        image: drone/drone-runner-docker:1
        env_file: .env
        ports:
            - "3000:3000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    drone-data:    
