version: "3.8"


services: 
    drone-ui:
        container_name: drone
        image: drone/drone:1
        env_file: .env
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - drone-data:/data

    drone-docker-runner:
        container_name: dronerunner1
        restart: unless-stopped
        image: drone/drone-runner-docker:1
        env_file: .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    drone-ssh-runner:
        container_name: dronerunner2
        image: drone/drone-runner-ssh
        restart: unless-stopped
        env_file: .env

volumes:
    drone-data:    
