version: "3.8"


services: 
    dind:
        privileged: true
        restart: unless-stopped
        container_name: jenkins-docker
        image: docker:dind
        volumes:
            - jenkins-data:/var/jenkins_home 
            - jenkins-docker-certs:/certs/client
        ports:
            - 2376:2376
        environment: 
            - DOCKER_TLS_CERTDIR=/certs
        
    jenkins:
        container_name: jenkins
        privileged: true
        restart: unless-stopped        
        build:
            context:  ./master
        ports:
            - "8080:8080"
            - "50000:50000"
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro

networks:
    jenkins:

volumes:
    jenkins-data:
    jenkins-docker-certs:
