version: "3.8"


services: 
    dind:
        privileged: true
        container_name: jenkins-docker
        image: docker:dind
        volumes:
            - jenkins-data:/var/jenkins_home 
            - jenkins-certs:/certs/client
        ports:
            - 2376:2376
        environment: 
            - DOCKER_TLS_CERTDIR=/certs
        
    jenkins:
        container_name: jenkins
        build:
            context:  ./master
        ports:
            - "8080:8080"
            - "50000:50000"
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro



    # jenkins:
    #     container_name: jenkins
    #     restart: always
    #     links:
    #         - "dind:docker"
    #     volumes:
    #         - ${HOST_DOCKER}:/var/run/docker.sock
    #         - jenkins:/var/jenkins_home
    #     ports:
    #         - "${HOST_WWW}:8080"
    #         - "${HOST_OTHER}:50000"        
    #     build:
    #         context: ./master 
    #         args:
    #             HOST_UID: ${HOST_UID}
    #             HOST_GID: ${HOST_GID}

networks:
    jenkins:

volumes:
    jenkins-data:
    jenkins-certs: